comercio/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.PaginaPrimera.as_view(), name="pagina-primera" ),
    url(r'^productos/$', views.PaginaProductos.as_view(), name="pagina-productos" ),
]

cursoPractica/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('comercio.urls', namespace = "comercio"))
]

comercio/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

comercio/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic.base import TemplateView

# Create your views here.
class PaginaPrimera(TemplateView):
    template_name = "estructura.html"

class PaginaProductos(TemplateView):
    template_name = "productos.html"

comercio/templates/estructura.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="../static/css/materialize.min.css">
    <link rel="stylesheet" href="../static/css/estructura.css">
    <meta charset="utf-8">
    <title>
    {% block 'title' %}
      Hola Mundo
    {% endblock %}
    </title>

  </head>
  <body>

      <div class="row">
        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">Card Title</span>
              <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
              <a href="#">This is a link</a>
            </div>
          </div>
        </div>
      </div>
      <a href="{% url "comercio:pagina-productos" %}">Segunda Pagina</a>
  </body>
</html>

comercio/templates/productos.html
{% extends "estructura.html" %}
{% block 'title' %}
  Productos
{% endblock %}